### ISSUE TITLE
Tarball 404s

### ISSUE THREAD

**Issue by JustAnotherArchivist** [tomazos/actcd19#4]
https://codesearch.isocpp.org/faq.html links to https://codesearch.isocpp.org/actcd19.tar.gz (why through a Google redirect?), but that URL leads to a 404. While the directory is available, mirroring 2.5 million files through that isn't exactly a great idea. Any chance the bulk download could be restored?

**Comment by tomazos** [comment]
Hi @JustAnotherArchivist, yeah weird not sure where the archive went.  Maybe some overzealous sys admin deleted it.  Anyway, I've restored it to a tar ball of the post-processed files.  The link https://codesearch.isocpp.org/actcd19.tar.gz should work again.

(The redirect is some oddity of google docs.  Need to rewrite FAQ in strait HTML at some stage.)

**Comment by JustAnotherArchivist** [comment]
Wonderful, thank you! I see that it is much smaller (5.43 GB) than what the FAQ page says (9.9 GB). Is that just due to different compression settings?

**Comment by tomazos** [comment]
Yeah I think it's because I packed up the post-processed files this time, whereas the original was the raw unprocessed file set.  So the 5GB version is deduplicated etc.  If you could let me know the file count within the archive that would be great.  It's supposed to be about 2,489,599.  That's the post processed number of files.  Before post processing file count was about 4 million from memory (so the ratio looks right 2.4/4 approx eq 5.4/9.9)

**Comment by JustAnotherArchivist** [comment]
Ah, makes sense. Yeah, there are exactly 2489599 files in it. Perfect, thanks! :-)
